general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

# 5 minutes
listener {
    timeout = 300
    on-timeout = hyprctl hyprsunset gamma 50
    on-resume = hyprctl hyprsunset gamma 100
}

# 10 minutes
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 15 minutes
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
