background = #000000
foreground = #e5e5e5
cursor-color = #ffffff
selection-background = #262626
selection-foreground = #ffffff

palette = 0=#171717
palette = 1=#cc241d
palette = 2=#b90606
palette = 3=#737373
palette = 4=#ff1111
palette = 5=#9a1c1c
palette = 6=#ffffff
palette = 7=#e5e5e5
palette = 8=#525252
palette = 9=#ef4444
palette = 10=#b90606
palette = 11=#a3a3a3
palette = 12=#cbd5e1
palette = 13=#dc2626
palette = 14=#eaeaea
palette = 15=#ffffff
